# -*- coding: utf-8 -*-
"""Graphing_Florence2_TrainVal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sOv0WLgEeBsNUgdEEOlzAy9oFq1uDtqq
"""

nan = float("NaN")
loss_per_epoch = [(2.0071769381824294, 1.1601671554424144), (1.1018818140029907, 1.1565129889382257), (1.0122899695446617, 1.1865068409177992), (0.9666330111654181, 1.2203340552471302), (0.9291087319976405, 1.2239184158819694), (0.9025580371681012, 1.2746615167017337), (0.8724158061178107, 1.2830640806092157), (0.8553347336618524, 1.3079335512938324), (0.8430803606384679, 1.3217434264995434), (0.8241476648732236, 1.3289751829924408), (1.1326487754520618, 1.2738825171082109), (1.0214648654586391, 1.2615868316756353), (0.9439002783674942, 1.2978006932470534), (0.8093416835132398, 1.4501760866906908), (0.7097498184756229, 1.611859416520154), (0.6020115720598321, 1.6982586979866028), (0.4930594819156747, 1.9638979744028162), (0.37165876540698506, 2.155383485334891), (0.28448220852174255, 2.3935737433256925), (0.23199545317574552, 2.4208534646917275), (7.013690008772047, 4.827779434345387), (4.926807539086592, 4.779771928434019), (4.783171869579115, 5.212442168483028), (4.685829925537109, 4.7648009017661765), (4.644257452613429, 4.719133394735831), (4.558566582830329, 4.827234480116102), (4.565751409530639, 4.842717612231219), (4.511614194669222, 4.806198526311804), (4.422813952596564, 5.065084086524116), (4.292995560796637, 5.065148989359538), (107.13817698830053, 37.597383145932795), (40.70967437342593, 17.483325428432888), (22.611796067890367, 15.990897390577528), (11.51233417611373, 19.496938069661457), (7.483519574215538, 6.717046702349627), (5.250240516662598, 6.388713395154035), (5.026388544785349, 5.606129557998092), (4.83402839459871, 5.322566191355388), (4.772257852554321, 5.305645730760363), (4.6493203765467594, 5.241829077402751), (nan, nan), (nan, nan), (nan, nan), (nan, nan), (nan, nan), (nan, nan), (nan, nan), (nan, nan), (nan, nan), (nan, nan)]

import matplotlib.pyplot as plt

run1 = loss_per_epoch[:10]
run2 = loss_per_epoch[10:20]
run3 = loss_per_epoch[20:30]
run4 = loss_per_epoch[30:40]
run5 = loss_per_epoch[40:]

run1_train = []
run1_valid = []
run2_train = []
run2_valid = []
run3_train = []
run3_valid = []
run4_train = []
run4_valid = []
run5_train = []
run5_valid = []

for i in range(10):
    run1_train.append(run1[i][0])
    run1_valid.append(run1[i][1])
    run2_train.append(run2[i][0])
    run2_valid.append(run2[i][1])
    run3_train.append(run3[i][0])
    run3_valid.append(run3[i][1])
    run4_train.append(run4[i][0])
    run4_valid.append(run4[i][1])
    run5_train.append(run5[i][0])
    run5_valid.append(run5[i][1])

plt.plot(run1_train, label='run1_train, 5e-6')  #LR = LR * (0.8 ** i)
plt.plot(run1_valid, label='run1_valid, 5e-6')
plt.plot(run2_train, label='run2_train, 5e-5')
plt.plot(run2_valid, label='run2_valid, 5e-5')
plt.plot(run3_train, label='run3_train, 5e-4')
plt.plot(run3_valid, label='run3_valid, 5e-4')
plt.plot(run4_train, label='run4_train, 5e-3')
plt.plot(run4_valid, label='run4_valid, 5e-3')

plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss, 10 Epochs, 4 total runs at different learning rates')
plt.legend()
plt.show()
plt.savefig('loss_per_epoch.png')

plt.plot(run1_train, label='run1_train, 5e-6')  #LR = LR * (0.8 ** i)
plt.plot(run1_valid, label='run1_valid, 5e-6')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss, 10 Epochs, 5e-6')
plt.legend()
plt.show()
plt.savefig('loss_per_epoch_5e-6.png')

plt.plot(run2_train, label='run2_train, 5e-5')
plt.plot(run2_valid, label='run2_valid, 5e-5')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss, 10 Epochs, 5e-5')
plt.legend()
plt.show()
plt.savefig('loss_per_epoch_5e-5.jpg')

plt.plot(run3_train, label='run3_train, 5e-4')
plt.plot(run3_valid, label='run3_valid, 5e-4')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss, 10 Epochs, 5e-4')
plt.legend()
plt.show()
plt.savefig('loss_per_epoch_5e-4.png')

plt.plot(run4_train, label='run4_train, 5e-3')
plt.plot(run4_valid, label='run4_valid, 5e-3')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss, 10 Epochs, 5e-3')
plt.legend()
plt.show()
plt.savefig('loss_per_epoch_5e-3.png')